import { createContext, useContext, useState, type ReactNode } from "react";

type Language = "ro" | "ru";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const ro: Record<string, string> = {
  "nav.home": "Acasa",
  "nav.about": "Despre Noi",
  "nav.services": "Servicii",
  "nav.gallery": "Galerie",
  "nav.booking": "Programari",
  "nav.contact": "Contact",
  "nav.bookNow": "Programeaza-te",
  "hero.subtitle": "BARBERSHOP PREMIUM IN CHISINAU",
  "hero.slogan": "Style, Precision, Confidence",
  "hero.description": "Experimenteaza arta tunsului la cel mai inalt nivel. Echipa noastra de profesionisti te asteapta cu servicii premium.",
  "hero.cta": "Programeaza-te Acum",
  "hero.services": "Vezi Serviciile",
  "about.label": "DESPRE NOI",
  "about.title": "Mai Mult Decat Un Barbershop",
  "about.p1": "Luca's Barbershop este locul unde traditia intalneste stilul modern. Fondat cu pasiune pentru arta barbieritului, salonul nostru din Chisinau ofera o experienta premium fiecarui client.",
  "about.p2": "Echipa noastra de barberi profesionisti combina tehnicile clasice cu tendintele actuale pentru a crea look-uri care definesc personalitatea fiecarui client.",
  "about.p3": "Ne mandrim cu atentia la detalii, atmosfera relaxanta si dedicarea fata de excelenta. La Luca's, nu doar tundem - cream incredere.",
  "about.years": "Ani de Experienta",
  "about.clients": "Clienti Multumiti",
  "about.barbers": "Barberi Profesionisti",
  "services.label": "SERVICIILE NOASTRE",
  "services.title": "Servicii Premium",
  "services.subtitle": "Fiecare serviciu este realizat cu precizie si atentie la detalii, folosind produse premium.",
  "services.bookService": "Programeaza",
  "services.currency": "MDL",
  "service.complex.name": "Complex Tuns + Barba",
  "service.complex.desc": "Pachet complet: tuns profesional si aranjare barba.",
  "service.haircut.name": "Tunsoare Barbati",
  "service.haircut.desc": "Tunsoare profesionala cu consultare personalizata.",
  "service.kids.name": "Tunsoare Copii",
  "service.kids.desc": "Tunsoare prietenoasa pentru cei mici.",
  "service.royalHead.name": "Ras ROYAL pe Cap",
  "service.royalHead.desc": "Ras complet al capului cu tehnica regala.",
  "service.royalBeard.name": "Ras ROYAL Barba",
  "service.royalBeard.desc": "Ras regal al barbii cu prosop cald.",
  "service.hairColor.name": "Vopsire Par",
  "service.hairColor.desc": "Colorare profesionala a parului.",
  "service.styling.name": "Aranjare",
  "service.styling.desc": "Styling profesional pentru orice ocazie.",
  "service.blackMask.name": "BLACK MASK",
  "service.blackMask.desc": "Masca neagra pentru curatarea profunda a porilor.",
  "service.wax.name": "Epilare Faciala (WAX)",
  "service.wax.desc": "Epilare cu ceara pentru o piele neteda.",
  "service.beardShape.name": "Modelare Barba",
  "service.beardShape.desc": "Conturare si modelare profesionala a barbii.",
  "service.beardColor.name": "Vopsire Barba",
  "service.beardColor.desc": "Colorare profesionala a barbii.",
  "service.eyebrowColor.name": "Vopsire Sprancene",
  "service.eyebrowColor.desc": "Colorare sprancene pentru un aspect definit.",
  "service.eyebrowShape.name": "Modelare Sprancene",
  "service.eyebrowShape.desc": "Modelare profesionala a sprancenelor.",
  "service.simpleHaircut.name": "Tunsoare Simpla",
  "service.simpleHaircut.desc": "Tunsoare rapida si eficienta.",
  "gallery.label": "GALERIE",
  "gallery.title": "Lucrarile Noastre",
  "gallery.subtitle": "Fiecare tunsoare este o opera de arta. Descopera stilurile create de echipa Luca's Barbershop.",
  "reviews.label": "RECENZII",
  "reviews.title": "Ce Spun Clientii",
  "reviews.subtitle": "Satisfactia clientilor nostri este cea mai buna recomandare.",
  "booking.label": "PROGRAMARI",
  "booking.title": "Programeaza-te Online",
  "booking.subtitle": "Completeaza formularul si te vom contacta pentru confirmare.",
  "booking.name": "Numele Complet",
  "booking.namePlaceholder": "Introdu numele tau",
  "booking.phone": "Numar de Telefon",
  "booking.phonePlaceholder": "+373 XXX XX XXX",
  "booking.service": "Serviciul Dorit",
  "booking.servicePlaceholder": "Selecteaza serviciul",
  "booking.date": "Data Preferata",
  "booking.datePlaceholder": "Selecteaza data",
  "booking.time": "Ora Preferata",
  "booking.timePlaceholder": "Selecteaza ora",
  "booking.message": "Mesaj Aditional",
  "booking.messagePlaceholder": "Orice detalii suplimentare...",
  "booking.submit": "Trimite Programarea",
  "booking.success": "Programarea a fost trimisa cu succes! Te vom contacta in curand.",
  "booking.callUs": "Sau suna-ne direct",
  "contact.label": "CONTACT",
  "contact.title": "Contacteaza-ne",
  "contact.subtitle": "Vino sa ne vizitezi sau contacteaza-ne pentru programari.",
  "contact.address": "Adresa",
  "contact.phone": "Telefon",
  "contact.social": "Social Media",
  "contact.hours": "Program",
  "contact.hoursValue": "Luni - Duminica: 10:00 - 19:00",
  "footer.rights": "Toate drepturile rezervate.",
  "footer.tagline": "Style, Precision, Confidence",
};

const ru: Record<string, string> = {
  "nav.home": "Главная",
  "nav.about": "О Нас",
  "nav.services": "Услуги",
  "nav.gallery": "Галерея",
  "nav.booking": "Запись",
  "nav.contact": "Контакты",
  "nav.bookNow": "Записаться",
  "hero.subtitle": "ПРЕМИУМ БАРБЕРШОП В КИШИНЁВЕ",
  "hero.slogan": "Style, Precision, Confidence",
  "hero.description": "Испытайте искусство стрижки на высшем уровне. Наша команда профессионалов ждёт вас с премиум услугами.",
  "hero.cta": "Записаться Сейчас",
  "hero.services": "Наши Услуги",
  "about.label": "О НАС",
  "about.title": "Больше Чем Барбершоп",
  "about.p1": "Luca's Barbershop - это место, где традиции встречают современный стиль. Основанный с любовью к искусству парикмахерского дела, наш салон в Кишинёве предлагает премиум опыт каждому клиенту.",
  "about.p2": "Наша команда профессиональных барберов сочетает классические техники с современными тенденциями для создания образов, определяющих индивидуальность каждого клиента.",
  "about.p3": "Мы гордимся вниманием к деталям, расслабляющей атмосферой и преданностью совершенству. В Luca's мы не просто стрижём - мы создаём уверенность.",
  "about.years": "Лет Опыта",
  "about.clients": "Довольных Клиентов",
  "about.barbers": "Профессиональных Барберов",
  "services.label": "НАШИ УСЛУГИ",
  "services.title": "Премиум Услуги",
  "services.subtitle": "Каждая услуга выполняется с точностью и вниманием к деталям, используя премиум продукты.",
  "services.bookService": "Записаться",
  "services.currency": "MDL",
  "service.complex.name": "Комплекс Стрижка + Борода",
  "service.complex.desc": "Полный пакет: профессиональная стрижка и оформление бороды.",
  "service.haircut.name": "Мужская Стрижка",
  "service.haircut.desc": "Профессиональная стрижка с персональной консультацией.",
  "service.kids.name": "Детская Стрижка",
  "service.kids.desc": "Дружелюбная стрижка для самых маленьких.",
  "service.royalHead.name": "Королевское Бритьё Головы",
  "service.royalHead.desc": "Полное бритьё головы королевской техникой.",
  "service.royalBeard.name": "Королевское Бритьё Бороды",
  "service.royalBeard.desc": "Королевское бритьё бороды с горячим полотенцем.",
  "service.hairColor.name": "Окрашивание Волос",
  "service.hairColor.desc": "Профессиональное окрашивание волос.",
  "service.styling.name": "Укладка",
  "service.styling.desc": "Профессиональная укладка для любого случая.",
  "service.blackMask.name": "BLACK MASK",
  "service.blackMask.desc": "Чёрная маска для глубокого очищения пор.",
  "service.wax.name": "Эпиляция Лица (WAX)",
  "service.wax.desc": "Восковая эпиляция для гладкой кожи.",
  "service.beardShape.name": "Моделирование Бороды",
  "service.beardShape.desc": "Профессиональное моделирование бороды.",
  "service.beardColor.name": "Окрашивание Бороды",
  "service.beardColor.desc": "Профессиональное окрашивание бороды.",
  "service.eyebrowColor.name": "Окрашивание Бровей",
  "service.eyebrowColor.desc": "Окрашивание бровей для выразительного вида.",
  "service.eyebrowShape.name": "Моделирование Бровей",
  "service.eyebrowShape.desc": "Профессиональное моделирование бровей.",
  "service.simpleHaircut.name": "Простая Стрижка",
  "service.simpleHaircut.desc": "Быстрая и эффективная стрижка.",
  "gallery.label": "ГАЛЕРЕЯ",
  "gallery.title": "Наши Работы",
  "gallery.subtitle": "Каждая стрижка - произведение искусства. Откройте стили, созданные командой Luca's Barbershop.",
  "reviews.label": "ОТЗЫВЫ",
  "reviews.title": "Что Говорят Клиенты",
  "reviews.subtitle": "Удовлетворённость наших клиентов - лучшая рекомендация.",
  "booking.label": "ЗАПИСЬ",
  "booking.title": "Запишитесь Онлайн",
  "booking.subtitle": "Заполните форму, и мы свяжемся с вами для подтверждения.",
  "booking.name": "Полное Имя",
  "booking.namePlaceholder": "Введите ваше имя",
  "booking.phone": "Номер Телефона",
  "booking.phonePlaceholder": "+373 XXX XX XXX",
  "booking.service": "Желаемая Услуга",
  "booking.servicePlaceholder": "Выберите услугу",
  "booking.date": "Предпочтительная Дата",
  "booking.datePlaceholder": "Выберите дату",
  "booking.time": "Предпочтительное Время",
  "booking.timePlaceholder": "Выберите время",
  "booking.message": "Дополнительное Сообщение",
  "booking.messagePlaceholder": "Любые дополнительные детали...",
  "booking.submit": "Отправить Запись",
  "booking.success": "Запись успешно отправлена! Мы свяжемся с вами в ближайшее время.",
  "booking.callUs": "Или позвоните нам напрямую",
  "contact.label": "КОНТАКТЫ",
  "contact.title": "Свяжитесь с Нами",
  "contact.subtitle": "Приходите к нам или свяжитесь для записи.",
  "contact.address": "Адрес",
  "contact.phone": "Телефон",
  "contact.social": "Социальные Сети",
  "contact.hours": "Расписание",
  "contact.hoursValue": "Понедельник - Воскресенье: 10:00 - 19:00",
  "footer.rights": "Все права защищены.",
  "footer.tagline": "Style, Precision, Confidence",
};

const translations: Record<Language, Record<string, string>> = { ro, ru };

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>("ro");

  const t = (key: string): string => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
